repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Use a recent version
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files
    -   id: detect-private-key

-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.11 # Updated to latest
    hooks:
    -   id: ruff # Changed from ruff-check to ruff, as per ruff-pre-commit's README for current versions
        args: [--fix, --exit-non-zero-on-fix]

-   repo: https://github.com/psf/black-pre-commit-mirror # Changed to mirror as per Black's docs
    rev: 25.1.0 # Updated to latest
    hooks:
    -   id: black
        # language_version: python3.11 # Or your project's target Python version
